simulation: false

robot_adaptor: "boxy-adaptors::BoxyAdaptorNoBaseWithGripper"

roi_frames:
  world:
    Ta: "base_footprint"
    Tb: "base_footprint"
  base:
    Ta: "base_link"
    Tb: "base_footprint"
  leftarm:
    Ta: "left_gripper_base_link"
#     Ta: "left_arm_flange_link"
    Tb: "base_footprint"
  llgripper:
    Ta: "left_gripper_gripper_left_link"
    Tb: "left_gripper_base_link"
  lrgripper:
    Ta: "left_gripper_gripper_right_link"
    Tb: "left_gripper_base_link"
  rightarm:
    Ta: "right_gripper_base_link"
#     Ta: "right_arm_flange_link"
    Tb: "base_footprint"
  rlgripper:
    Ta: "right_gripper_gripper_left_link"
    Tb: "right_gripper_base_link"
  rrgripper:
    Ta: "right_gripper_gripper_right_link"
    Tb: "right_gripper_base_link"
  camera:
    Ta: "pw070_frame_out"
    Tb: "base_footprint"

joint_weights:
  triangle_base_joint: 20.0
  head_pan_joint:      0.1
  head_tilt_joint:     0.1

solver_config:
  max_iterations:     300
  max_cpu_time:        0.0
  sample_time:         0.004
  convergence_crit:    0.0001 #note: exponential notation only from YAML1.2
  regularization:      0.0001
  initialization_time: 3

adaptor_config:
  right_arm_0_joint:
    stiffness:          200.0
    damping:            0.7
  right_arm_1_joint:  
    stiffness:          160.0
    damping:            0.7  
  right_arm_2_joint:
    stiffness:          80.0
    damping:            0.7 
  right_arm_3_joint:
    stiffness:          80.0
    damping:            0.7 
  right_arm_4_joint:
    stiffness:          80.0
    damping:            0.7 
  right_arm_5_joint:    
    stiffness:          80.0
    damping:            0.7 
  right_arm_6_joint:    
    stiffness:          80.0
    damping:            0.7  
